### PR TITLE
Coverage report 

### LINKED ISSUE #31: No Coverage report
Hi,

It would be nice to generate coverage report and check it via https://coveralls.io/
Additionally this will allow coverage badge url which can be used for this repo.

All it takes is create coveralls account and add this repository to coveralls account.
Coverage reports for Coveralls can be generated by adding luacov-coveralls in .travis.yml

### PR DESCRIPTION
**Pull request by brudnyhenry**
Resolves #31

### CODE REVIEW

**Comment by Trojan295** [comment]
@CsatariGergely, could you enable access to this repo by https://coveralls.io?

@brudnyhenry, also modification of the README.md is necessary to show the badge right? Let's wait, till the repo is added to coveralls.io and add it then.

**Comment by CsatariGergely** [comment]
@Trojan295 I think I enabled the repo on coveralls (https://coveralls.io/github/nokia/kong-oidc)

**Comment by Trojan295** [comment]
Great! @brudnyhenry, could you update the PR with the badge?

**Comment by brudnyhenry** [comment]
Updated. Now coverage badge should  be updated after new commit to kong-oidc master branch

**Pull request merged**
