### PR TITLE
Add config for `introspection_endpoint_auth_method`

### PR DESCRIPTION
**Pull request by tommilligan**
It was not possible to set the auth method for introspection through the config.

This was found when trying to use token introspection with [ORY Hydra](https://github.com/ory/hydra), which requires [Basic](https://github.com/ory/fosite/blob/482e431032f61f7290de46a1592016feecfdf3cd/introspection_request_handler.go#L109) or OAuth authorisation for introspection.

This PR:
- adds [`introspection_endpoint_auth_method` as required by lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc/blob/a0c310fd46085ce6b0ba0e94c4f9e719b35599bf/lib/resty/openidc.lua#L1389)
- adds this value to config, schema, readme
- adds unit test
- does not add a default value for backwards compatibility (will remain as `nil`)

### CODE REVIEW

**Comment by tommilligan** [comment]
@Trojan295 are you interested in help maintaining this project? I'm currently working on features to match Kong's enterprise [OAuth Introspection plugin](https://docs.konghq.com/enterprise/0.33-x/plugins/oauth2-introspection/)

**Comment by zandbelt** [comment]
@tommilligan I'm interested but I don't have the bandwidth to contribute.

**Comment by Trojan295** [comment]
@tommilligan, sorry for the late response, but I'm out of this project a bit.

Still, it looks OK from my side. Can you also squash the commits to one?

@phirvone @tsyrjanen , can you try to prepare a new release for LuaRocks? There were a few PR accepted since the last release.

**Comment by tommilligan** [comment]
@Trojan295 thanks, no worries at all

**Pull request merged**
